### ISSUE TITLE
EveContractResolver ResolvePropertyName issue

### ISSUE THREAD

**Issue by ahmed-sherien** [nicolaiarocci/Eve.NET#1]
The contract resolver transform the property name to lower case which breaks the case sensitive REST Service I'm using ... I think it should use the `JsonProperty` attribute

**Comment by nicolaiarocci** [comment]
Just curious, are you using a Eve-powered API in the backend?

**Comment by ahmed-sherien** [comment]
@nicolaiarocci my bad I thought it's a generic type of rest client ... thx for the enlightenment
