### ISSUE TITLE
Indentation and spacing

### ISSUE THREAD

**Issue by pedro2555** [nicolaiarocci/Eve.NET#3]
Indentation and spacing is all messed up on my side. Is that something off the editor you're using?

Just one example

![image](https://user-images.githubusercontent.com/1645623/37075429-aadb4ca8-21c9-11e8-8020-b4ab0b53bc0f.png)
thats VS 2017

**Comment by nicolaiarocci** [comment]
I've been switching between multiple editors, that probably didn't help.
